### PR TITLE
Feature/ui enhancement map id 365

### LINKED ISSUE #365: Displaying Map on full screen
UI Enhancement to Map: 
Displaying Google Map on full screen, with 'Public Dataset'  button as an overlay. An info icon(i) will be
displayed at the top right corner, which tells user what green trail and purple circle represents.

### PR DESCRIPTION
**Pull request by ArchanaNair**
Close #365

### CODE REVIEW

**Comment by tstirrat** [comment]
Hi, can you provide some screenshots?

**Comment by tstirrat** [comment]
Thanks for working on this, too

**Comment by ArchanaNair** [comment]
Please find below screenshot and let me know your suggestions.

Screenshot_2020-04-07-22-33-02-327_edu mit privatekit
Screenshot_2020-04-07-22-36-10-959_edu mit privatekit

**Comment by ArchanaNair** [comment]
Screenshot 2020-04-09 at 2 09 43 PM

Test cases are getting failed after taking pull from develop branch. Attached is the screen for reference. The error is showing in Welcome.js which I haven't touch. So please someone can look into it.

**Comment by tstirrat** [comment]
using `@testing-library/react-native`'s render method is async aware and should help with this:


```js
import {render} from '@testing-library/react-native';

it('renders correctly', () => {
  const {asJSON} = render(<App />);

  expect(asJSON()).toMatchSnapshot();
});
```

**Comment by ArchanaNair** [comment]
Closing this PR, as the UI has changed and new PR has been raised after implementing the enhancement  in latest UI. 
New PR-  https://github.com/PrivateKit/private-kit/pull/12

**Pull request closed without merging**
